### ISSUE TITLE
nlp.spot not returning entity array, but rather an object

### ISSUE THREAD

**Issue by nfons** [Kroid/angular-nlp-compromise#1]
nlp.spot("joe carter loves toronto"); is supposed to return [joe carter, toronto].

instead the following:
    var spot =nlp.spot("joe carter loves toronto");
    $log.info(spot);

returns an object:

![image](https://cloud.githubusercontent.com/assets/882236/6337139/bf0845f4-bb75-11e4-8c17-e82af1e38323.png)

**Comment by Kroid** [comment]
Hello! This bug from parent lib, I opened issue there.

**Comment by nfons** [comment]
Root issue now fixed. can you merge new nlp?

**Comment by Kroid** [comment]
Completed, thx.
