### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by spencermountain** [Kroid/angular-nlp-compromise#4]
hey george, we've been working on a v2 re-write of nlp_compromise, and lots has changed.
are you interested in maintaining your fork? wanna check it out?
https://github.com/spencermountain/nlp_compromise/tree/2.0
Hope you're well,
cheers

**Comment by Kroid** [comment]
Hi Spencer! 
I'm planing update this repo after you'll create v2 release. Or should I create v2 branch with angular-version now?

**Comment by spencermountain** [comment]
great thanks!
whenever you'd like. if things go well, i hope to release in 2 weeks or so. 
I'll write a migration-page or something, and let you know. Lots has changed and improved.

**Comment by Kroid** [comment]
OK
